name: Build

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  Build1:
    runs-on: ubuntu-latest
    name: Build1
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          curl ifconfig.me
          python3 -m http.server 8000
