name: Build

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  Build1:
    runs-on: ubuntu-latest
    name: Build1
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          python3 updateip.py
          sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 8000 -j ACCEPT
          sudo netfilter-persistent save
          python3 -m http.server 8000
